version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - apt-get update
      - apt-get install -y google-chrome-stable

  pre_build:
    commands:
      - echo pre-build phase
  build:
    commands:
      - echo build-phase the docker image and run it as container
      - docker build -t myapp .
      - docker run -it myapp
  post_build:
    commands:
      - echo post-build phase
