version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - echo pre-build phase
  build:
    commands:
      - echo build-phase the docker image and run it as container
      - docker build -t myapp .
      - docker run -it myapp
  post_build:
    commands:
      - echo post-build phase
