version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - echo Restoring NuGet packages...
      - dotnet restore
  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Post build action
